export const gasComponents = [
  ["../../00-overall/02-header/header.html", "header"],
  ["../../04-gas/gas-hero/gas-hero.html", "main"],
  ["../../04-gas/gas-section-one/gas-section-one.html", "main"],
  ["../../04-gas/gas-section-two/gas-section-two.html", "main"],
  ["../../04-gas/gas-section-three/gas-section-three.html", "main"],
  ["../../04-gas/gas-section-four/gas-section-four.html", "main"],
  ["../../04-gas/gas-section-five/gas-section-five.html", "main"],
  ["../../04-gas/gas-section-six/gas-section-six.html", "main"],
  ["../../04-gas/gas-section-seven/gas-section-seven.html", "main"],
  ["../../04-gas/gas-section-eight/gas-section-eight.html", "main"],
  ["../../04-gas/gas-section-nine/gas-section-nine.html", "main"],
  ["../../04-gas/gas-section-ten/gas-section-ten.html", "main"],
  ["../../04-gas/gas-section-eleven/gas-section-eleven.html", "main"],
  ["../../00-overall/04-footer/footer.html", "footer"],
];